---
version: "3.8"
services:

  service1:

    image: docker.io/joshuahigginson1/melodie_service1:latest

    environment:
      - FLASK_ENV

      - SERVICE_2_URL
      - SERVICE_3_URL
      - SERVICE_4_URL

      - FILES_DIRECTORY

      - PRODUCTION_DB_USERNAME
      - PRODUCTION_DB_USERPASS
      - PRODUCTION_DB
      - PRODUCTION_DATABASE_ADDRESS

      - PRODUCTION_SECRET_KEY

      - DEVELOPMENT_DB_USERNAME
      - DEVELOPMENT_DB_USERPASS
      - DEVELOPMENT_DB
      - DEVELOPMENT_DATABASE_ADDRESS

      - DEV_SECRET_KEY

      - TESTING_DB_USERNAME
      - TESTING_DB_USERPASS
      - TESTING_DB
      - TESTING_DATABASE_ADDRESS

      - TESTING_SECRET_KEY

    build:
      context: ./service1

    ports:
      - target: 5001
        published: 5001
        protocol: tcp

    depends_on:
      - service2
      - service3
      - service4

  service2:

    image: docker.io/joshuahigginson1/melodie_service2:latest

    environment:
      - FLASK_ENV='nigelfaragesucks'

    build:
      context: ./service2

    ports:
      - target: 5002
        published: 5002
        protocol: tcp

  service3:

    image: docker.io/joshuahigginson1/melodie_service3:latest

    environment:
      - FLASK_ENV

    build:
      context: ./service3

    ports:
      - target: 5003
        published: 5003
        protocol: tcp

  service4:

    image: docker.io/joshuahigginson1/melodie_service4:latest

    environment:
      - FLASK_ENV

      - PNG_DIRECTORY
      - MIDI_DIRECTORY

      - SERVICE_2_URL
      - SERVICE_3_URL

    build:
      context: ./service4

    ports:
      - target: 5004
        published: 5004
        protocol: tcp
...