- hosts: all
  become: true

  vars:
    - gluster_mount_dir: /mnt/gluster
      gluster_brick_dir: /srv/gluster/brick
      gluster_brick_name: gluster

  roles:
    - RESEARCHTHIS.firewall
    - RESEARCHTHIS.glusterfs

  - name: Install Git and GlusterFS Dependencies
    apt:
      name: {{ item }}
      state: latest
      update_cache: yes

    with_items:
      - git
      - glusterfs-server
      - glusterfs-client
      - glusterfs-common
      - nfs-kernel-server

  - name: Enable GlusterFS on Boot
    service:
      name: {{ glusterfs_daemon }}
      state: started
      enabled: yes

  - name: Probe GlusterFS Nodes
    shell: "gluster peer probe {{ item }}"
    with_items:
      - "{{ groups['all'] }}"

    - name: Ensure that the Gluster directories exist with an ansible loop.
      file:
        path: {{ item }}
        state: directory
        mode: u=rw,g=r,o-rwx

      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Configure our Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        rebalance: yes
        replicas: 2
        cluster: "{{ groups['all'] }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true

    - name: Ensure that the Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted








  - name: Create Directory Example
    file:
      path: /tmp/devops_directory
      state: directory