---
- name: Add common APT repositories.
  apt_repository:
    repo: ppa:gluster/glusterfs-7

- name: Install common Git and GlusterFS dependencies.
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes

  with_items:
    - git
    - software-properties-common
    - glusterfs-server
    - glusterfs-client
    - glusterfs-common
    - nfs-kernel-server

- name: Enable GlusterFS on Boot
  service:
    name: glusterd
    state: started
    enabled: yes

- name: Ensure that our Gluster brick and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: www-data
    mode: u=rw,g=rw,o=r

  with_items:
    - "{{ gluster_brick_dirs }}"
    - "{{ gluster_mount_dir }}"

# - name: Probe GlusterFS Nodes
#   shell: "gluster peer probe {{ item }}"
#   with_items: groups.all

- name: Probe each node, and add them to our GlusterFS stack.
  gluster_peer:
    state: present
    nodes: "{{ groups['all'] }}"
  delegate_to: "{{ groups['all'][0] }}"

- name: Configure our Gluster volume, before starting it.
  gluster_volume:
    state: present
    name: "gv0"
    brick: "{{ gluster_brick_dirs }}"
    rebalance: yes
    replicas: 2
    cluster: "{{ groups['all'] }}"
  run_once: true

- name: Start our Gluster volume.
  gluster_volume:
    state: started
    name: "gv0"
  run_once: true

- name: Ensure that the Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
...