---
- name: Add common APT repositories.
  apt_repository:
    repo: ppa:gluster/glusterfs-7

- name: Install common Git and GlusterFS dependencies.
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes

  with_items:
    - git
    - software-properties-common
    - glusterfs-server
    - glusterfs-client
    - glusterfs-common
    - nfs-kernel-server

- name: Enable GlusterFS on Boot.
  service:
    name: glusterd
    state: restarted
    enabled: yes

- name: Ensure that our Gluster brick and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: www-data
    mode: u=rw,g=rw,o=r

  with_items:
    - "{{ gluster_brick_dir_dict }}"
    - "{{ gluster_mount_dir }}"

- name: Probe GlusterFS Nodes from our driver.
  shell: "gluster peer probe {{ item }}"
  delegate_to: "{{ groups['jenkins_ansible_driver'][0] }}"
  with_items: {{ groups['glusterfs'] }}

- name: Probe our GlusterFS driver from another node, to initialise stack.
  shell: "gluster peer probe {{ groups['jenkins_ansible_driver'][0] }}"
  delegate_to: "{{ groups['glusterfs'][0] }}"

- name: Configure our Gluster volume, before starting it.
  gluster_volume:
    state: present
    name: "gv0"
    bricks: "{{ gluster_brick_dirs }}"
    rebalance: yes
    replicas: 2
    cluster: "{{ groups['all'] }}"
    force: yes  # Bricks are being created in our root partition.
  run_once: true

- name: Start our Gluster volume.
  gluster_volume:
    state: started
    name: "gv0"
  run_once: true

- name: Ensure that the Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
...