apiVersion: v1
kind: Namespace

metadata:
  name: testing

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: testing
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-melodie-deployment

  template:
    metadata:
      namespace: testing
      labels:
        app: nginx-melodie-deployment

    spec:
      containers:
      - name: melodie-nginx-container
        image: docker.io/joshuahigginson1/melodie_nginx:latest
        ports:
          - name: port80
            protocol: TCP
            hostPort: 80
            containerPort: 80


