apiVersion: apps/v1
kind: Deployment

metadata:
  name: service3-deployment
  namespace: testing
  labels:
    app: service3

spec:
  replicas: 2
  selector:
    matchLabels:
      app: service3

  template:
    metadata:
      namespace: testing
      labels:
        app: service3

    spec:
      containers:
      - name: service3-container
        image: docker.io/joshuahigginson1/melodie_service3:latest
        env:
          - name: FLASK_ENV
            value: testing

        ports:
          - name: port5003
            protocol: TCP
            hostPort: 5003
            containerPort: 5003