apiVersion: apps/v1
kind: Deployment

metadata:
  name: service2Deployment
  namespace: testing
  labels:
    app: service2

spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2

  template:
    metadata:
      namespace: testing
      labels:
        app: service2

    spec:
      containers:
      - name: service2Container
        image: docker.io/joshuahigginson1/melodie_service2:latest
        env:
          - name: FLASK_ENV
            value: testing

        ports:
          - name: port5002
            protocol: TCP
            hostPort: 5002
            containerPort: 5002